### ISSUE TITLE
Review traffic_light_config

### ISSUE THREAD

**Issue by murli-9585** [ablacklama/System-Integration#12]
Check if contents in traffic_light_config can be updated for better perf. Ex: Img size etc., If none, feel free to close.

**Comment by ablacklama** [comment]
SSD takes a 300x300x3 input. But it doesn't really matter what we feed to the model because it will resize it. The question here is really how we can only make the program resize the image once. If it's being resized from the camera and then again for the model, then we have a performance drop. We should set the output size in that config file to be the default so only tensorflow is resizing the image.

**Comment by MikeZhu92** [comment]
BTW, opencv resize function is pretty fast.

**Comment by ablacklama** [comment]
As far as I can tell opencv isn’t on Carla so we can’t use it.
Tf resize is fast too
